from sqlmodel import SQLModel, Field
from typing import Optional
import time


class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(index=True, nullable=False, unique=True)
    hashed_password: str
    full_name: Optional[str] = None
    is_active: bool = Field(default=True)
    created_at: int = Field(default_factory=lambda: int(time.time()))


class UserPreference(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    keywords: Optional[str] = Field(default="")    # comma-separated keywords
    sources: Optional[str] = Field(default="")     # comma-separated sources
    match_mode: str = Field(default="or")          # "or" or "and"
    created_at: int = Field(default_factory=lambda: int(time.time()))


class Bookmark(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    title: str
    url: str
    added_at: int = Field(default_factory=lambda: int(time.time()))


# MSNRR Models
class ArticleClick(SQLModel, table=True):
    """Track user clicks on articles for engagement history scoring."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    article_url: str = Field(index=True)
    article_title: Optional[str] = None
    clicked_at: int = Field(default_factory=lambda: int(time.time()))


class EngagementHistory(SQLModel, table=True):
    """Aggregated engagement metrics per user for EHS calculation."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True, unique=True)
    total_clicks: int = Field(default=0)
    total_bookmarks: int = Field(default=0)
    clicked_urls: Optional[str] = Field(default="")  # JSON array of URLs
    bookmarked_urls: Optional[str] = Field(default="")  # JSON array of URLs
    last_updated: int = Field(default_factory=lambda: int(time.time()))


# NDLRM Models
class UserKnowledgeProfile(SQLModel, table=True):
    """User's knowledge profile with topic embeddings for NDLRM."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True, unique=True)
    topic_scores: Optional[str] = Field(default="{}")  # JSON: {"ai": 0.8, "ml": 0.5, ...}
    target_career: Optional[str] = None  # e.g., "AI Engineer", "Software Engineer"
    last_updated: int = Field(default_factory=lambda: int(time.time()))


class LearningRoadmap(SQLModel, table=True):
    """Weekly learning roadmaps generated by NDLRM."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    week_start: int  # Unix timestamp for week start
    roadmap_data: str  # JSON string with week_plan, skills, practice_questions, resources
    target_career: Optional[str] = None  # e.g., "AI Engineer", "Data Scientist"
    generated_at: int = Field(default_factory=lambda: int(time.time()))